import React, { useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { Sparkles, ArrowRight, BookOpen, Lock, Image, RefreshCw, Layers } from "lucide-react";

export default function LandingPage() {
  const [tokenInput, setTokenInput] = useState("");
  const navigate = useNavigate();

  const handleGo = (e) => {
    e.preventDefault();
    if (tokenInput.trim()) {
      navigate(`/u/${tokenInput.trim()}`);
    }
  };

  const features = [
    {
      icon: BookOpen,
      title: "Context Preserved",
      description: "Don't just store files. Write the complete stories and emotions behind every photograph or video clip.",
      color: "var(--color-primary)",
      tag: "JOURNAL CORE"
    },
    {
      icon: Lock,
      title: "Invite Link Access",
      description: "Pure private storage. Access is completely restricted to unique invite tokens generated by the vault admin.",
      color: "var(--color-secondary)",
      tag: "SECURE NODE"
    },
    {
      icon: Layers,
      title: "Timeline Activity Heatmap",
      description: "Visualize the active phases of your life with contribution-style activity logs and density maps.",
      color: "var(--color-accent)",
      tag: "LIFE MATRIX"
    }
  ];

  return (
    <div className="min-h-screen bg-[#FAF3E0] dot-grid text-[#1E293B] overflow-x-hidden flex flex-col justify-between">
      {/* ── Header Navbar ─────────────────────────────────────────────────── */}
      <header className="bg-[#FFFDF9] border-b-3 border-[#1E293B] sticky top-0 z-50">
        <div className="page-container h-16 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <div className="w-8 h-8 rounded-full bg-[#FBBF24] border-2 border-[#1E293B] flex items-center justify-center shadow-[2px_2px_0px_0px_rgba(30,41,59,1)]">
              <Sparkles size={14} strokeWidth={2.5} />
            </div>
            <span className="font-display font-black text-lg uppercase tracking-wider text-[#1E293B]">
              Memory<span className="text-[#8B5CF6]">Vault</span>
            </span>
          </div>

          <div className="flex items-center gap-3">
            <Link
              to="/admin"
              className="btn-ghost text-xs uppercase"
              style={{ padding: "0.45rem 1.25rem" }}
            >
              Password Portal
            </Link>
          </div>
        </div>
      </header>

      {/* ── Hero Grid ────────────────────────────────────────────────────── */}
      <section className="page-container py-16 text-center max-w-4xl relative">
        {/* Large Decorative Amber Shape */}
        <div className="absolute w-64 h-64 rounded-full bg-[#FBBF24] opacity-80 border-3 border-[#1E293B] shadow-[6px_6px_0px_0px_rgba(30,41,59,1)] top-10 left-1/2 -translate-x-1/2 -z-10"></div>

        <div className="inline-flex items-center gap-1.5 bg-[#FFFDF9] border-2 border-[#1E293B] rounded-full px-5 py-1.5 text-xs font-black tracking-wide shadow-[3px_3px_0px_0px_rgba(30,41,59,1)] mb-8 uppercase">
          <Sparkles className="text-[#8B5CF6]" size={12} strokeWidth={2.5} />
          Personal Media Archive & Journal
        </div>

        <h1 className="font-display font-black text-4xl sm:text-6xl tracking-tight leading-none mb-6 text-[#1E293B]">
          Preserving the Context <br />
          <span className="bg-[#FFFDF9] px-4 py-1 border-3 border-[#1E293B] inline-block -rotate-1 shadow-[4px_4px_0px_rgba(244,114,182,1)]">
            Behind the Memory
          </span>
        </h1>

        <p className="font-sans text-base md:text-lg text-[#1E293B] font-medium max-w-xl mx-auto mb-10 leading-relaxed">
          More than just storage. MemoryVault links your pictures and videos with the stories that make them live. Private, secure, and context-focused.
        </p>

        {/* ── Direct Token Gateway Card ────────────────────────────────────── */}
        <div className="max-w-md mx-auto bg-[#FFFDF9] border-3 border-[#1E293B] rounded-xl p-6 shadow-[6px_6px_0px_0px_rgba(30,41,59,1)] text-left mb-16">
          <h3 className="font-display font-black text-sm uppercase tracking-wider text-[#1E293B] mb-3">
            🔑 Enter Vault Invitation
          </h3>
          <form onSubmit={handleGo} className="flex gap-2 flex-col sm:flex-row">
            <input
              type="text"
              placeholder="e.g. abx92k"
              value={tokenInput}
              onChange={(e) => setTokenInput(e.target.value)}
              className="input-field shrink-0 uppercase tracking-widest text-center"
            />
            <button
              type="submit"
              className="btn-primary shadow-[2px_2px_0px_0px_rgba(30,41,59,1)] hover:translate-x-0.5 hover:shadow-[1px_1px_0px_0px_rgba(30,41,59,1)] whitespace-nowrap cursor-pointer text-xs"
            >
              Open Vault <ArrowRight size={14} strokeWidth={2.5} />
            </button>
          </form>
          <p className="text-[10px] font-bold text-[#5C6F84] uppercase mt-3">
            If you received a full link (e.g. /u/abx92k), click it directly or paste the code above.
          </p>
        </div>
      </section>

      {/* ── Bouncy Scrolling Marquee ───────────────────────────────────────── */}
      <section className="bg-[#8B5CF6] border-t-3 border-b-3 border-[#1E293B] py-3 overflow-hidden whitespace-nowrap">
        <div className="animate-marquee inline-block text-sm sm:text-base font-display font-black text-white tracking-widest uppercase">
          ★ PHOTO JOURNALING ★ VIDEO STORIES ★ MONTHLY ACTIVITY HEATMAPS ★ SECURE INVITES ★ PRIVATE STORAGE ★ PHOTO JOURNALING ★ VIDEO STORIES ★ MONTHLY ACTIVITY HEATMAPS ★
        </div>
      </section>

      {/* ── Features Sticker Matrix ────────────────────────────────────────── */}
      <section className="page-container py-16 max-w-5xl">
        <div className="text-center mb-12">
          <h2 className="section-header text-[#1E293B] mb-2 uppercase">
            Preserve Your Life's Nodes
          </h2>
          <p className="text-sm font-bold text-[#5C6F84] uppercase max-w-md mx-auto">
            Tactile controls and memory tools engineered to bridge pixels with personal stories.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
          {features.map((feat, i) => {
            const Icon = feat.icon;
            return (
              <div
                key={i}
                className="pop-shadow-card bg-[#FFFDF9] p-8 rounded-xl relative pt-12"
              >
                <div
                  className="absolute w-12 h-12 rounded-full border-2 border-[#1E293B] flex items-center justify-center top-[-24px] left-6 shadow-[2px_2px_0px_0px_rgba(30,41,59,1)]"
                  style={{ backgroundColor: feat.color }}
                >
                  <Icon size={20} color="#FFF" strokeWidth={2.5} />
                </div>
                <div className="text-[10px] font-black text-[#5C6F84] text-right uppercase mb-2">
                  // {feat.tag}
                </div>
                <h3 className="font-display font-black text-base text-[#1E293B] mb-2 uppercase">
                  {feat.title}
                </h3>
                <p className="text-xs text-[#5C6F84] leading-relaxed font-sans font-medium">
                  {feat.description}
                </p>
              </div>
            );
          })}
        </div>
      </section>

      <section className="page-container py-8 text-center max-w-xl">
        <div className="bg-[#FFFDF9] border-3 border-[#1E293B] rounded-lg p-6 shadow-[5px_5px_0px_0px_rgba(30,41,59,1)]">
          <h4 className="font-display font-black text-sm uppercase text-[#1E293B] mb-2">
            Forgot or want to change your password?
          </h4>
          <p className="text-xs text-[#5C6F84] font-medium mb-4">
            Access the password portal to reset your password back to default or set a new custom password.
          </p>
          <Link to="/admin" className="btn-secondary text-xs uppercase shadow-[2px_2px_0px_0px_rgba(30,41,59,1)]">
            Open Password Portal
          </Link>
        </div>
      </section>

      {/* ── Footer ─────────────────────────────────────────────────────────── */}
      <footer className="border-t-3 border-[#1E293B] bg-[#FFFDF9] py-8 text-center text-xs font-display font-bold text-[#5C6F84] tracking-wider uppercase mt-8">
        © 2026 MemoryVault // Stable Grid, Deep Context // Built for Placements.
      </footer>
    </div>
  );
}
